import libs += certifiable-inference%liba{certifiable_inference}

exes = exe{ \
  certifiable_inference_xor_gate \
  certifiable_inference_edge_detection \
  certifiable_inference_debug_conv \
  certifiable_inference_debug_pool \
  }

exe{certifiable_inference_xor_gate}: c{xor_gate}
exe{certifiable_inference_edge_detection}: c{edge_detection}
exe{certifiable_inference_debug_conv}: c{debug_conv}
exe{certifiable_inference_debug_pool}: c{debug_pool}

./: $exes
